/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package platillostipicos.appdesktop;

/**
 *
 * @author edefl
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        meIniciarSession = new javax.swing.JMenu();
        meRegister = new javax.swing.JMenu();
        meSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meIniciarSession.setText("Iniciar Session");
        meIniciarSession.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meIniciarSessionMenuSelected(evt);
            }
        });
        jMenuBar1.add(meIniciarSession);

        meRegister.setText("Registrarse");
        meRegister.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meRegisterMenuSelected(evt);
            }
        });
        jMenuBar1.add(meRegister);

        meSalir.setText("Salir");
        meSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meSalirMenuSelected(evt);
            }
        });
        jMenuBar1.add(meSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meIniciarSessionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meIniciarSessionMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_meIniciarSessionMenuSelected

    private void meRegisterMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meRegisterMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_meRegisterMenuSelected

    private void meSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meSalirMenuSelected
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_meSalirMenuSelected


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu meIniciarSession;
    private javax.swing.JMenu meRegister;
    private javax.swing.JMenu meSalir;
    // End of variables declaration//GEN-END:variables
}
